"""5

Revision ID: 16ad6bfdf6a1
Revises: ef6661e9d51c
Create Date: 2025-07-14 18:52:28.069812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16ad6bfdf6a1'
down_revision: Union[str, None] = 'ef6661e9d51c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contractor_access', 'owner_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contractor_access', sa.Column('owner_id', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###
