"""2

Revision ID: 1a9e6a5720af
Revises: 8793d5967b14
Create Date: 2025-07-14 18:38:49.288801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a9e6a5720af'
down_revision: Union[str, None] = '8793d5967b14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contractor_access', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.drop_constraint(None, 'contractor_access', type_='foreignkey')
    op.create_foreign_key(None, 'contractor_access', 'contractors', ['owner_id'], ['id'])
    op.drop_column('contractor_access', 'contractor_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contractor_access', sa.Column('contractor_id', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'contractor_access', type_='foreignkey')
    op.create_foreign_key(None, 'contractor_access', 'contractors', ['contractor_id'], ['id'])
    op.drop_column('contractor_access', 'owner_id')
    # ### end Alembic commands ###
